### ISSUE TITLE
Color issue on Centos 7?

### ISSUE THREAD

**Issue by borestad** [chauncey-garrett/zsh-prompt-garrett#1]
Nice theme! :)

This is how it looks while installed on a Centos 7.1 machine and ssh'ing in via iTerm2 (osx yosemite). Something I've missed?

![skarmavbild 2015-07-17 kl 15 48 39](https://cloud.githubusercontent.com/assets/286455/8748527/5b7210be-2c9b-11e5-99bc-1d37413e31eb.png)

**Comment by chauncey-garrett** [comment]
> Nice theme! :)

Thanks! :)

> This is how it looks while installed on a Centos 7.1 machine and ssh'ing in via iTerm2 (osx yosemite). Something I've missed?

Yep, I made the prompt so that it would change color on `ssh` and as the root user. See https://github.com/chauncey-garrett/zsh-prompt-garrett#change-host-color-when-on-ssh.

If you'd like a different color, or no color at all, you'll need to edit this portion of the prompt:

``` zsh
# Determine prompt, user and host colors
if [[ "$EUID" = "0" ]] || [[ "$USER" = 'root' ]]
then # root user
    # set colors
    eval prompt_garrett_color_user=${3:-'${red}'}
    eval prompt_garrett_color_host=${3:-'${red}'}
    eval prompt_garrett_color_prompt=${3:-'${red}'}
    # set style
    eval prompt_garrett_user='%S${prompt_garrett_color_user}%n%s'
    eval prompt_garrett_host='${prompt_garrett_color_host}%m' # hostname up to first . (dot) (use %M for full hostname)
    eval prompt_garrett_location='${prompt_garrett_user}${cyan}@${prompt_garrett_host}' # user@host.name
elif [[ -n "$SSH_CLIENT" || -n "$SSH2_CLIENT" ]]
then # on SSH
    # set colors
    eval prompt_garrett_color_user=${3:-'${green}'}
    eval prompt_garrett_color_host=${3:-'${yellow}'}
    eval prompt_garrett_color_prompt=${3:-'${yellow}'}
    # set style
    eval prompt_garrett_user='%S${prompt_garrett_color_user}%n%s'
    eval prompt_garrett_host='${prompt_garrett_color_host}%m' # hostname up to first . (dot) (use %M for full hostname)
    eval prompt_garrett_location='${prompt_garrett_user}${cyan}@${prompt_garrett_host}' # user@host.name
else # normal user
    # set colors
    eval prompt_garrett_color_user=${1:-'${green}'}
    eval prompt_garrett_color_host=${1:-'${green}'}
    eval prompt_garrett_color_prompt=${1:-'${grey}'}
    # set style
    eval prompt_garrett_user=''
    eval prompt_garrett_host='${prompt_garrett_color_host}%m' # hostname up to first . (dot) (use %M for full hostname)
    eval prompt_garrett_location='${prompt_garrett_user}${cyan}@${prompt_garrett_host}' # user@host.name
fi
```

Color choices come from this portion:

``` zsh
for color in black red green yellow blue magenta cyan white grey
do
    eval $color='%F{${(L)color}}'
    eval ${color}_bold='%B{${(L)color}}'
done
```

If you primarily work over ssh and don't want a color change, just drop the `elif` block. I do recommend keeping the root portion since you don't want to stay the root user for long.

Your prompt text, on the other hand should be grey. Can you confirm what color it is while on both `ssh` and on your local machine?

**Comment by chauncey-garrett** [comment]
@borestad Feel free to reopen if you had trouble with the color settings.
