### ISSUE TITLE
Root color issue on Ubuntu

### ISSUE THREAD

**Issue by zimmicz** [chauncey-garrett/zsh-prompt-garrett#2]
Hi,
I get [\e[31;1;46m][\u] \w $[\e[0m]  instead of colored root when sudoing. 
Using zsh version 5.0.2 on Ubuntu 14.04.

**Comment by chauncey-garrett** [comment]
Do you mean that it prints that string out? Can you take a snapshot?

**Comment by zimmicz** [comment]
![screenshot from 2015-11-07 17 50 12](https://cloud.githubusercontent.com/assets/6543598/11016154/6b7d3494-8578-11e5-9c2e-3d0d8f0498fd.png)
Here you go.

On Sat, Nov 7, 2015 at 5:47 PM, Chauncey Garrett notifications@github.com
wrote:

> Do you mean that it prints that string out? Can you take a snapshot?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chauncey-garrett/zsh-prompt-garrett/issues/2#issuecomment-154722788
> .

## 

Michal Zimmermann (zimmi)
WWW: http://www.zimmi.cz

**Comment by chauncey-garrett** [comment]
It's using `$SUDO_PS1`, which should just be a backup prompt. Can you `echo $EUID` and `echo $USER` as the root user for me?

**Comment by zimmicz** [comment]
`echo $EUID` -> 0
`echo $USER` -> root

**Comment by chauncey-garrett** [comment]
Ok that's what I expected. Working on it now.

**Comment by chauncey-garrett** [comment]
What happens when you `sudo -s`?

`sudo -i` simulates an initial login but I'm surprised that it kept the `$SUDO_PS1` environment variable around.

For me, `sudo -i` resets the environment, while `sudo -s` does not. I'm on OS X so there may something different between our systems (BSD vs GNU).

Also, the `SUDO_PS1` variable is specific to the `bash` shell, which is likely why your seeing it. One way to check what shell you are as root would be to run `echo $SHELL`. Let me know what that outputs after running `sudo -i` and `sudo -s` as well.

**Comment by zimmicz** [comment]
`sudo -s` followed by `echo $SHELL` gives /bin/zsh and it actually works, the prompt turns red.
`sudo -i` followed by `echo $SHELL` gives /usr/bin/zsh and it doesn't work, it prints the string out.

Update: hmm, even if I do `sudo chsh -s /bin/zsh` and sudo to root, it still prints the string out.

**Comment by chauncey-garrett** [comment]
Closing old issue but feel free to reopen if you still have it.
