### ISSUE TITLE
Re-sizing the terminal window formatting wackiness

### ISSUE THREAD

**Issue by zachlendon** [chauncey-garrett/zsh-prompt-garrett#22]
![image](https://user-images.githubusercontent.com/518116/31084588-6739380a-a75a-11e7-8450-a08f48329aea.png)

Same window, resized
![image](https://user-images.githubusercontent.com/518116/31084649-93951edc-a75a-11e7-884c-8d1a21a3309e.png)

I realize this may be hard to fix, but posting it as it is an "issue".

**Comment by chauncey-garrett** [comment]
As is, I don't know that there's much that can be done about this. The reason for the wackiness is that the number of characters needed to create the top line is calculated prior to display, and printed out at the time of the prompt creation. It's a hack, really.

The bottom right portion is set with RPROMPT and that's why it detaches and correctly resizes.

Since AFAIK there's nothing that can be done about this, I'm closing the issue; however, if anyone has ideas about how to fix it we can definitely reopen.
