### ISSUE TITLE
Keep path visible after clearing the screen

### ISSUE THREAD

**Issue by zimmicz** [chauncey-garrett/zsh-prompt-garrett#5]
If you run `clear` command, both lines of prompt stay visible on top of the screen.
However, when the clear command is run with `Ctrl + L`, only the second line with arrows is visible, so you effectively lose track of where you are in your directory structure.

Ubuntu 14.04.

**Comment by zimmicz** [comment]
Any thoughts on this matter?

**Comment by nomasprime** [comment]
I'm having the same problem.

**Comment by nomasprime** [comment]
@chauncey-garrett I'd be happy to take a look at this too if you could give me some pointers.

**Comment by chauncey-garrett** [comment]
I've known about this issue for a while but have yet to come up with a good solution to fix it.

The issue results from the top half of the prompt being drawn during the during `prompt_garrett_precmd` while the bottom half is created by exporting the `PROMPT` environment variable. This hack was the only solution I was able to come up with to have the right prompt show up below the top line. If I added a newline as part of the left prompt to make the final two line prompt, the right prompt would be visible on the top line instead of the bottom. So that's why the code does what it does.

I don't know the exact difference between the `clear` command and `^L` but they are different commands. `^L` will trigger `zle`'s [`clear-screen`](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html) (under 18.6.6) which "clears the screen and redraws the prompt" and doesn't appear to run `prompt_garrett_precmd`. Note that `precmd` is by [definition](http://zsh.sourceforge.net/Doc/Release/Functions.html) just that: 

> `precmd` Executed before each prompt. Note that precommand functions are not re-executed simply because the command line is redrawn, as happens, for example, when a notification about an exiting job is displayed.

The best solution I've been able to come up with is to add this keybinding to your `zshrc`:

```
bindkey -s '^l' 'clear\n'
```

It works but you can visible see that the keybinding is typing `clear` before it redraws the screen; this is not ideal.

Without a way to keep the right prompt on the bottom line, I'm afraid that's the best I can do at this time. I'm open to suggestions and further conversation but am closing this issue for now as I can see no way around it.
