### ISSUE TITLE
PS1 line drawing in iTerm2 howto

### ISSUE THREAD

**Issue by yeongsheng-tan** [chauncey-garrett/zsh-prompt-garrett#8]
This is what worked for me, both in iTerm2

Goto your iTerm2/3 Preferences -> Profiles -> Terminal -> Terminal Emulation -> 
- Character Encoding:
  Set to 'Unicode (UTF-8)'
- Report Terminal Type:
  Set to 'xterm-256color'

**Comment by leoj3n** [comment]
I seem to have lines that look solid in iTerm beta:

```
┌─( ~/.h/r/prezto λ:master | ◼ 892b17b )───────────────────────────────────( ruby:ruby-2.2.1 @3n )─┐
└─❱❱❱                                                                                 +4938 7:48 ❰─┘
```

but I can highlight the pieces individually.

I have changed many settings over time and have a custom font so not a fresh install and not sure what is changed from defaults, however I do have the same settings you mentioned.

**Comment by chauncey-garrett** [comment]
The issue with line drawing and iTerm2 I mentioned in the README.md appears to be fixed. As of v3.0.8 (and perhaps earlier -- I think I first noticed it was fixed with the upgrade to v3), line drawing works!

@yeongsheng-tan Thanks for providing your settings. Those are the same settings I've been using -- I haven't changed them -- even before I upgrade iTerm2 to v3.
